### ISSUE TITLE
you are assigning an undefined state

### ISSUE THREAD

**Issue by Qlink84** [Pittini/iobroker-Timer#10]
<html>
<body>

javascript.0 | 2022-03-03 07:25:55.954 | warn | at processImmediate (internal/timers.js:464:21)
-- | -- | -- | --
javascript.0 | 2022-03-03 07:25:55.954 | warn | at Immediate._onImmediate (C:\iobroker\iob01\node_modules\@iobroker\js-controller-adapter\src\lib\adapter\adapter.js:5909:56)
javascript.0 | 2022-03-03 07:25:55.954 | warn | at Object.stateChange (C:\iobroker\iob01\node_modules\iobroker.javascript\main.js:530:29)
javascript.0 | 2022-03-03 07:25:55.954 | warn | at Object.callback (C:\iobroker\iob01\node_modules\iobroker.javascript\lib\sandbox.js:1082:38)
javascript.0 | 2022-03-03 07:25:55.954 | warn | at Object.<anonymous> (script.js.Timer_Script_2_2_0:1240:21)
javascript.0 | 2022-03-03 07:25:55.954 | warn | at setState (C:\iobroker\iob01\node_modules\iobroker.javascript\lib\sandbox.js:1437:20)
javascript.0 | 2022-03-03 07:25:55.938 | warn | You are assigning a undefined to the state "javascript.0.Timer.Template.SwitchTargetSmartName" which expects a string. Please fix your code to use a string or change the state type to undefined. This warning might become an error in future versions.

</body>
</html>

**Comment by Pittini** [comment]
More information please.
